-- В этом миграционном скрипте внесены изменения в таблицы, чтобы привести их к правильной форме.

ALTER TABLE Post
ALTER COLUMN PostName SET NOT NULL,
ALTER COLUMN Salary SET NOT NULL;

ALTER TABLE Employee
ALTER COLUMN FirstName SET NOT NULL,
ALTER COLUMN LastName SET NOT NULL,
ALTER COLUMN Birthday SET NOT NULL,
ALTER COLUMN PhoneNumber SET NOT NULL,
ADD CONSTRAINT chk_phone CHECK (PhoneNumber LIKE '+7%');

ALTER TABLE Store
ALTER COLUMN Adress SET NOT NULL,
ALTER COLUMN StoreArea SET NOT NULL;

ALTER TABLE Supplier
ALTER COLUMN SupplierName SET NOT NULL,
ALTER COLUMN Email SET NOT NULL,
ALTER COLUMN Department SET NOT NULL;

ALTER TABLE Product
ALTER COLUMN ProductName SET NOT NULL,
ALTER COLUMN Department SET NOT NULL,
ALTER COLUMN ProductCost SET NOT NULL,
ADD CONSTRAINT chk_product_cost CHECK (ProductCost > 10.00);

ALTER TABLE Purchase
ALTER COLUMN PurchaseDate SET NOT NULL,
ALTER COLUMN PurchaseTime SET NOT NULL,
ALTER COLUMN ProductID SET NOT NULL,
ALTER COLUMN EmployeeID SET NOT NULL,
ALTER COLUMN StoreID SET NOT NULL;
